[platformio]
default_envs = dev


[env]
framework = arduino
monitor_speed = 115200


; Configuração comum a todos os targets ESP8266
[esp8266]
platform = espressif8266
upload_speed = 921600
platform_packages =
    framework-arduinoespressif8266 @ symlink:///home/gabriel/workspace/Arduino-esp8266
; Decisão de projeto:
; Todo firmware eTomada Lite para ESP8266 usa layout de flash de 1 MB,
; independentemente da capacidade física de flash da placa.
board_build.ldscript = eagle.flash.1m.ld

; LN882H:
; usa o layout padrão de 2 MB do LibreTiny/generic-ln882h,
; preservando as regiões nativas de APP, OTA e storage.
[ln882h]
platform = libretiny
upload_speed = 115200


[env:dev]
extends = esp8266
board = esp12e
upload_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
monitor_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
build_flags =
    -D HW_DEV


[env:sonoff-mini]
extends = esp8266
board = esp01_1m
; ESP8285 do Sonoff Mini R1 usa flash em modo DOUT
board_build.flash_mode = dout
build_flags =
    -D HW_SONOFF_MINIR1


[env:wemos]
extends = esp8266
board = d1_mini
upload_port = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
monitor_port = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
build_flags =
    -D HW_WEMOS


[env:cozylife]
; extends = ln882h
platform = symlink:///home/gabriel/workspace/libretiny
board = generic-ln882h
build_flags =
    -D ETOMADA_LIBRETINY
    -D HW_COZY