[platformio]
default_envs = dev

[env]
platform = espressif8266
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.flash_mode = dout
board_build.f_flash = 40000000L
board_build.f_cpu = 80000000L
board_build.ldscript = eagle.flash.1m.ld

build_flags =
    -D ETOMADA_LITE

[env:dev]
board = esp12e
upload_port = /dev/serial/by-path/pci-0000:04:00.0-usb-0:1.2:1.0-port0
monitor_port = /dev/serial/by-path/pci-0000:04:00.0-usb-0:1.2:1.0-port0
build_flags =
    -D HW_DEV

[env:sonoff-mini]
board = esp01_1m
build_flags =
    -D HW_SONOFF_MINIR1
#    -D RELE_GPIO=12
#    -D BTN_GPIO=0
#    -D S1_GPIO=4
#    -D LED_GPIO=13
#    -D JUMPER_GPIO=16
